/*
 * Generated by PeakRDL-cpp. Do not edit manually.
 *
 * SPDX-License-Identifier: CC0-1.0
 */

#pragma once

#include <cassert>
#include <array>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <memory>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <utility>

namespace wide_demo {

using addr_t = std::uint32_t;
using data_t = std::uint32_t;
static constexpr std::uint8_t kAccessWidth = 32;
static constexpr bool kCheckWriteRange = true;

// Bus adapter contract (documented-only):
//   data_t read(addr_t addr);
//   void write(addr_t addr, data_t value);

namespace detail {

enum class AccessMode : std::uint8_t { na, r, w, rw, rw1, w1 };
using signed_data_t = std::make_signed_t<data_t>;
using signed_input_t = std::intmax_t;
using unsigned_input_t = std::uintmax_t;

template <typename BusT, bool ThrowOnError>
class Context {
public:
    explicit Context(BusT& bus_ref, addr_t base)
        : bus(&bus_ref), base_address(base), ok_flag(true), last_error_msg() {}

    void fail(const char* message) {
        if constexpr (ThrowOnError) {
            throw std::runtime_error(message);
        } else {
            ok_flag = false;
            last_error_msg = message;
        }
    }

    bool ok() const { return ok_flag; }
    const std::string& last_error() const { return last_error_msg; }
    void clear_error() {
        ok_flag = true;
        last_error_msg.clear();
    }

    BusT* bus;
    addr_t base_address;

private:
    bool ok_flag;
    std::string last_error_msg;
};

static constexpr std::size_t kAccessBytes = kAccessWidth / 8;
static constexpr std::size_t kMaxRegWords = (64 + kAccessWidth - 1) / kAccessWidth;
using reg_storage_t = std::array<data_t, kMaxRegWords>;

inline data_t bitmask_for_width(std::uint8_t width) {
    if (width >= kAccessWidth) {
        return std::numeric_limits<data_t>::max();
    }
    return static_cast<data_t>((data_t{1} << width) - data_t{1});
}

template <typename ElemT, std::size_t N>
class NodeArray {
public:
    ElemT& operator[](std::size_t idx) {
        assert(idx < N);
        assert(items_[idx] != nullptr);
        return *items_[idx];
    }
    const ElemT& operator[](std::size_t idx) const {
        assert(idx < N);
        assert(items_[idx] != nullptr);
        return *items_[idx];
    }
    constexpr std::size_t size() const { return N; }
    void set(std::size_t idx, std::unique_ptr<ElemT> elem) {
        assert(idx < N);
        items_[idx] = std::move(elem);
    }
private:
    std::array<std::unique_ptr<ElemT>, N> items_{};
};

template <typename BusT, bool ThrowOnError>
class RegisterState {
public:
    RegisterState(
        Context<BusT, ThrowOnError>& ctx,
        addr_t reg_offset,
        std::uint8_t reg_width,
        std::uint8_t word_count,
        reg_storage_t reset_value,
        reg_storage_t read_mask,
        reg_storage_t write_only_mask,
        reg_storage_t rclr_mask,
        reg_storage_t rset_mask,
        reg_storage_t singlepulse_mask,
        bool shadow_write_supported)
        : ctx_(ctx),
          offset_(reg_offset),
          reg_width_(reg_width),
          word_count_(word_count),
          read_shadow_(reset_value),
          write_shadow_(reset_value),
          read_mask_(read_mask),
          write_only_mask_(write_only_mask),
          rclr_mask_(rclr_mask),
          rset_mask_(rset_mask),
          singlepulse_mask_(singlepulse_mask),
          shadow_write_supported_(shadow_write_supported),
          dirty_(false) {}

    addr_t address() const { return static_cast<addr_t>(ctx_.base_address + offset_); }
    bool dirty() const { return dirty_; }
    bool supports_shadow_write() const { return shadow_write_supported_; }

    reg_storage_t read_hw() {
        reg_storage_t raw{};
        for (std::uint8_t idx = 0; idx < word_count_; ++idx) {
            raw[idx] = to_bus_data(ctx_.bus->read(word_address(idx)), idx);
        }
        apply_hw_read(raw);
        return raw;
    }

    data_t read_hw_scalar() {
        return read_hw()[0];
    }

    void shadow_read_hw() {
        (void)read_hw();
    }

    void flush() {
        flush_impl(true);
    }

    void flush_always() {
        flush_impl(false);
    }

    data_t read_field_hw_scalar(std::uint8_t lsb, std::uint8_t width) {
        return extract_scalar(read_hw(), lsb, width);
    }

    data_t read_field_shadow_scalar(std::uint8_t lsb, std::uint8_t width) const {
        return extract_scalar(read_shadow_, lsb, width);
    }

    data_t read_field_staged_scalar(std::uint8_t lsb, std::uint8_t width) const {
        return extract_scalar(write_shadow_, lsb, width);
    }

    template <std::size_t WordCount>
    std::array<data_t, WordCount> read_field_hw_array(std::uint8_t lsb, std::uint8_t width) {
        return extract_array<WordCount>(read_hw(), lsb, width);
    }

    template <std::size_t WordCount>
    std::array<data_t, WordCount> read_field_shadow_array(std::uint8_t lsb, std::uint8_t width) const {
        return extract_array<WordCount>(read_shadow_, lsb, width);
    }

    template <std::size_t WordCount>
    std::array<data_t, WordCount> read_field_staged_array(std::uint8_t lsb, std::uint8_t width) const {
        return extract_array<WordCount>(write_shadow_, lsb, width);
    }

    void shadow_write_unsigned(
        std::uint8_t lsb,
        std::uint8_t width,
        unsigned_input_t value,
        const char* field_name) {
        if (!shadow_write_supported_) {
            ctx_.fail("field.wr_shadow.write() is unsupported for this register");
            return;
        }
        const data_t limit = bitmask_for_width(width);
        if constexpr (kCheckWriteRange) {
            if (value > static_cast<unsigned_input_t>(limit)) {
                ctx_.fail(field_name);
                return;
            }
        }
        const data_t narrowed = static_cast<data_t>(value);
        reg_storage_t next = write_shadow_;
        insert_scalar(next, lsb, width, narrowed);
        if (next != write_shadow_) {
            write_shadow_ = next;
            dirty_ = true;
        }
    }

    template <std::size_t WordCount>
    void shadow_write_array(
        std::uint8_t lsb,
        std::uint8_t width,
        const std::array<data_t, WordCount>& value,
        const char* field_name) {
        if (!shadow_write_supported_) {
            ctx_.fail("field.wr_shadow.write() is unsupported for this register");
            return;
        }
        if constexpr (kCheckWriteRange) {
            if (!check_array<WordCount>(width, value)) {
                ctx_.fail(field_name);
                return;
            }
        }
        reg_storage_t next = write_shadow_;
        insert_array(next, lsb, width, value);
        if (next != write_shadow_) {
            write_shadow_ = next;
            dirty_ = true;
        }
    }

    void shadow_write_signed(
        std::uint8_t lsb,
        std::uint8_t width,
        signed_input_t value,
        const char* field_name) {
        if (!shadow_write_supported_) {
            ctx_.fail("field.wr_shadow.write() is unsupported for this register");
            return;
        }
        if constexpr (kCheckWriteRange) {
            if (!check_signed(width, value)) {
                ctx_.fail(field_name);
                return;
            }
        }
        const data_t encoded_value = encode_signed(width, value);
        shadow_write_unsigned(lsb, width, encoded_value, field_name);
    }

    void direct_write_unsigned(
        std::uint8_t lsb,
        std::uint8_t width,
        unsigned_input_t value,
        AccessMode sw_mode,
        bool singlepulse,
        const char* field_name) {
        const data_t limit = bitmask_for_width(width);
        if constexpr (kCheckWriteRange) {
            if (value > static_cast<unsigned_input_t>(limit)) {
                ctx_.fail(field_name);
                return;
            }
        }

        reg_storage_t base_value{};
        if (sw_mode == AccessMode::w || sw_mode == AccessMode::w1) {
            base_value = write_shadow_;
        } else {
            const reg_storage_t hw_value = read_hw();
            base_value = merge_read_with_write_only(hw_value);
        }

        const data_t narrowed = static_cast<data_t>(value);
        insert_scalar(base_value, lsb, width, narrowed);
        write_hw(base_value);
        insert_scalar(write_shadow_, lsb, width, narrowed);
        insert_scalar(read_shadow_, lsb, width, narrowed);
        dirty_ = false;
        if (singlepulse) {
            clear_range(write_shadow_, lsb, width);
            clear_range(read_shadow_, lsb, width);
        }
    }

    template <std::size_t WordCount>
    void direct_write_array(
        std::uint8_t lsb,
        std::uint8_t width,
        const std::array<data_t, WordCount>& value,
        AccessMode sw_mode,
        bool singlepulse,
        const char* field_name) {
        if constexpr (kCheckWriteRange) {
            if (!check_array<WordCount>(width, value)) {
                ctx_.fail(field_name);
                return;
            }
        }
        reg_storage_t base_value{};
        if (sw_mode == AccessMode::w || sw_mode == AccessMode::w1) {
            base_value = write_shadow_;
        } else {
            const reg_storage_t hw_value = read_hw();
            base_value = merge_read_with_write_only(hw_value);
        }
        insert_array(base_value, lsb, width, value);
        write_hw(base_value);
        insert_array(write_shadow_, lsb, width, value);
        insert_array(read_shadow_, lsb, width, value);
        dirty_ = false;
        if (singlepulse) {
            clear_range(write_shadow_, lsb, width);
            clear_range(read_shadow_, lsb, width);
        }
    }

    void direct_write_signed(
        std::uint8_t lsb,
        std::uint8_t width,
        signed_input_t value,
        AccessMode sw_mode,
        bool singlepulse,
        const char* field_name) {
        if constexpr (kCheckWriteRange) {
            if (!check_signed(width, value)) {
                ctx_.fail(field_name);
                return;
            }
        }
        const data_t encoded = encode_signed(width, value);
        direct_write_unsigned(lsb, width, encoded, sw_mode, singlepulse, field_name);
    }

private:
    void flush_impl(bool only_if_dirty) {
        if (!shadow_write_supported_) {
            ctx_.fail("wr_shadow.flush() is unsupported for this register");
            return;
        }
        if (only_if_dirty && !dirty_) {
            return;
        }
        write_hw(write_shadow_);
        dirty_ = false;
        apply_singlepulse_clear();
    }
    void apply_hw_read(const reg_storage_t& raw) {
        for (std::uint8_t idx = 0; idx < word_count_; ++idx) {
            const data_t readable = read_mask_[idx];
            read_shadow_[idx] = static_cast<data_t>((read_shadow_[idx] & static_cast<data_t>(~readable)) | (raw[idx] & readable));
            write_shadow_[idx] = static_cast<data_t>((write_shadow_[idx] & static_cast<data_t>(~readable)) | (raw[idx] & readable));
            write_shadow_[idx] = static_cast<data_t>((write_shadow_[idx] & static_cast<data_t>(~rclr_mask_[idx])) | rset_mask_[idx]);
            read_shadow_[idx] &= word_mask(idx);
            write_shadow_[idx] &= word_mask(idx);
        }
    }

    static bool check_signed(std::uint8_t width, signed_input_t value) {
        if (width == 0) {
            return false;
        }
        if (width >= kAccessWidth) {
            const signed_input_t min_value = static_cast<signed_input_t>(std::numeric_limits<signed_data_t>::min());
            const signed_input_t max_value = static_cast<signed_input_t>(std::numeric_limits<signed_data_t>::max());
            return value >= min_value && value <= max_value;
        }
        const data_t sign_bit = static_cast<data_t>(data_t{1} << (width - 1));
        const signed_input_t min_value = -static_cast<signed_input_t>(sign_bit);
        const signed_input_t max_value = static_cast<signed_input_t>(sign_bit - data_t{1});
        return value >= min_value && value <= max_value;
    }

    static data_t encode_signed(std::uint8_t width, signed_input_t value) {
        const data_t limit = bitmask_for_width(width);
        return static_cast<data_t>(static_cast<data_t>(value) & limit);
    }

    template <std::size_t WordCount>
    static bool check_array(std::uint8_t width, const std::array<data_t, WordCount>& value) {
        for (std::size_t idx = 0; idx < WordCount; ++idx) {
            const std::uint8_t used = word_width_for_field_word(width, idx);
            if (used == 0 && value[idx] != data_t{0}) {
                return false;
            }
            if (used > 0 && used < kAccessWidth && (value[idx] & static_cast<data_t>(~bitmask_for_width(used))) != data_t{0}) {
                return false;
            }
        }
        return true;
    }

    static std::uint8_t word_width_for_field_word(std::uint8_t width, std::size_t idx) {
        const std::size_t consumed = idx * kAccessWidth;
        if (consumed >= width) {
            return 0;
        }
        const std::size_t remaining = width - consumed;
        return static_cast<std::uint8_t>(remaining > kAccessWidth ? kAccessWidth : remaining);
    }

    data_t to_bus_data(data_t value, std::uint8_t word_idx) const {
        return static_cast<data_t>(value & word_mask(word_idx));
    }

    data_t word_mask(std::uint8_t word_idx) const {
        const std::uint16_t consumed = static_cast<std::uint16_t>(word_idx) * kAccessWidth;
        if (consumed >= reg_width_) {
            return data_t{0};
        }
        const std::uint16_t remaining = static_cast<std::uint16_t>(reg_width_ - consumed);
        return bitmask_for_width(static_cast<std::uint8_t>(remaining > kAccessWidth ? kAccessWidth : remaining));
    }

    addr_t word_address(std::uint8_t word_idx) const {
        return static_cast<addr_t>(address() + static_cast<addr_t>(word_idx * kAccessBytes));
    }

    void write_hw(const reg_storage_t& value) {
        for (std::uint8_t idx = 0; idx < word_count_; ++idx) {
            ctx_.bus->write(word_address(idx), to_bus_data(value[idx], idx));
        }
    }

    reg_storage_t merge_read_with_write_only(const reg_storage_t& hw_value) const {
        reg_storage_t out{};
        for (std::uint8_t idx = 0; idx < word_count_; ++idx) {
            out[idx] = static_cast<data_t>((hw_value[idx] & static_cast<data_t>(~write_only_mask_[idx])) | (write_shadow_[idx] & write_only_mask_[idx]));
            out[idx] &= word_mask(idx);
        }
        return out;
    }

    static data_t extract_scalar(const reg_storage_t& src, std::uint8_t lsb, std::uint8_t width) {
        data_t out = 0;
        std::uint8_t remaining = width;
        std::uint8_t bit = lsb;
        std::uint8_t out_shift = 0;
        while (remaining > 0) {
            const std::uint8_t word = bit / kAccessWidth;
            const std::uint8_t bit_in_word = bit % kAccessWidth;
            const std::uint8_t available = static_cast<std::uint8_t>(kAccessWidth - bit_in_word);
            const std::uint8_t chunk = remaining < available ? remaining : available;
            const data_t chunk_value = static_cast<data_t>((src[word] >> bit_in_word) & bitmask_for_width(chunk));
            out = static_cast<data_t>(out | static_cast<data_t>(chunk_value << out_shift));
            remaining = static_cast<std::uint8_t>(remaining - chunk);
            bit = static_cast<std::uint8_t>(bit + chunk);
            out_shift = static_cast<std::uint8_t>(out_shift + chunk);
        }
        return out;
    }

    template <std::size_t WordCount>
    static std::array<data_t, WordCount> extract_array(const reg_storage_t& src, std::uint8_t lsb, std::uint8_t width) {
        std::array<data_t, WordCount> out{};
        for (std::size_t idx = 0; idx < WordCount; ++idx) {
            const std::uint8_t chunk_width = word_width_for_field_word(width, idx);
            if (chunk_width != 0) {
                out[idx] = extract_scalar(src, static_cast<std::uint8_t>(lsb + idx * kAccessWidth), chunk_width);
            }
        }
        return out;
    }

    static void insert_scalar(reg_storage_t& dst, std::uint8_t lsb, std::uint8_t width, data_t value) {
        std::uint8_t remaining = width;
        std::uint8_t bit = lsb;
        std::uint8_t in_shift = 0;
        while (remaining > 0) {
            const std::uint8_t word = bit / kAccessWidth;
            const std::uint8_t bit_in_word = bit % kAccessWidth;
            const std::uint8_t available = static_cast<std::uint8_t>(kAccessWidth - bit_in_word);
            const std::uint8_t chunk = remaining < available ? remaining : available;
            const data_t chunk_mask = bitmask_for_width(chunk);
            const data_t word_mask_value = static_cast<data_t>(chunk_mask << bit_in_word);
            const data_t chunk_value = static_cast<data_t>(((value >> in_shift) & chunk_mask) << bit_in_word);
            dst[word] = static_cast<data_t>((dst[word] & static_cast<data_t>(~word_mask_value)) | chunk_value);
            remaining = static_cast<std::uint8_t>(remaining - chunk);
            bit = static_cast<std::uint8_t>(bit + chunk);
            in_shift = static_cast<std::uint8_t>(in_shift + chunk);
        }
    }

    template <std::size_t WordCount>
    static void insert_array(reg_storage_t& dst, std::uint8_t lsb, std::uint8_t width, const std::array<data_t, WordCount>& value) {
        for (std::size_t idx = 0; idx < WordCount; ++idx) {
            const std::uint8_t chunk_width = word_width_for_field_word(width, idx);
            if (chunk_width != 0) {
                insert_scalar(dst, static_cast<std::uint8_t>(lsb + idx * kAccessWidth), chunk_width, value[idx]);
            }
        }
    }

    static void clear_range(reg_storage_t& dst, std::uint8_t lsb, std::uint8_t width) {
        insert_scalar(dst, lsb, width, data_t{0});
    }

    void apply_singlepulse_clear() {
        for (std::uint8_t idx = 0; idx < word_count_; ++idx) {
            write_shadow_[idx] = static_cast<data_t>(write_shadow_[idx] & static_cast<data_t>(~singlepulse_mask_[idx]));
            read_shadow_[idx] = static_cast<data_t>(read_shadow_[idx] & static_cast<data_t>(~singlepulse_mask_[idx]));
        }
    }

    Context<BusT, ThrowOnError>& ctx_;
    addr_t offset_;
    std::uint8_t reg_width_;
    std::uint8_t word_count_;
    reg_storage_t read_shadow_;
    reg_storage_t write_shadow_;
    reg_storage_t read_mask_;
    reg_storage_t write_only_mask_;
    reg_storage_t rclr_mask_;
    reg_storage_t rset_mask_;
    reg_storage_t singlepulse_mask_;
    bool shadow_write_supported_;
    bool dirty_;
};

} // namespace detail

template <typename BusT, bool ThrowOnError>
class Wide6432WideRegReg {
public:
    static constexpr bool kShadowWriteSupported = true;

    explicit Wide6432WideRegReg(detail::Context<BusT, ThrowOnError>& ctx, addr_t reg_offset)
        : state_(ctx, reg_offset, 64, 2, detail::reg_storage_t{static_cast<data_t>(0x0ull), static_cast<data_t>(0x0ull)}, detail::reg_storage_t{static_cast<data_t>(0xFFFFFFFFull), static_cast<data_t>(0xFFFFFFFFull)}, detail::reg_storage_t{static_cast<data_t>(0x0ull), static_cast<data_t>(0x0ull)}, detail::reg_storage_t{static_cast<data_t>(0x0ull), static_cast<data_t>(0x0ull)}, detail::reg_storage_t{static_cast<data_t>(0x0ull), static_cast<data_t>(0x0ull)}, detail::reg_storage_t{static_cast<data_t>(0x0ull), static_cast<data_t>(0x0ull)}, kShadowWriteSupported)
        , rd_shadow(this)
        , wr_shadow(this)
        , data(this)
    {}

    detail::reg_storage_t read() { return state_.read_hw(); }
    bool supports_shadow_write() const { return kShadowWriteSupported; }
    addr_t address() const { return state_.address(); }

    class RdShadowOps {
    public:
        explicit RdShadowOps(Wide6432WideRegReg* owner) : owner_(owner) {}
        void read_hw() { owner_->state_.shadow_read_hw(); }
    private:
        Wide6432WideRegReg* owner_;
    };

    class WrShadowOps {
    public:
        explicit WrShadowOps(Wide6432WideRegReg* owner) : owner_(owner) {}
        void flush() { owner_->state_.flush(); }
        void flush_always() { owner_->state_.flush_always(); }
        bool dirty() const { return owner_->state_.dirty(); }
    private:
        Wide6432WideRegReg* owner_;
    };

    RdShadowOps rd_shadow;
    WrShadowOps wr_shadow;

    class Wide6432WideRegReg_data_Field {
    public:
        static constexpr std::uint8_t LSB = 0;
        static constexpr std::uint8_t MSB = 63;
        static constexpr std::uint8_t WIDTH = 64;
        static constexpr std::size_t WORD_COUNT = 2;
        static constexpr detail::AccessMode SW = detail::AccessMode::rw;
        static constexpr bool SINGLEPULSE = false;

        explicit Wide6432WideRegReg_data_Field(Wide6432WideRegReg* owner) : owner_(owner), rd_shadow(this), wr_shadow(this) {}

        std::array<data_t, WORD_COUNT> read() {
            return owner_->state_.template read_field_hw_array<WORD_COUNT>(LSB, WIDTH);
        }

        void write(const std::array<data_t, WORD_COUNT>& value) {
            owner_->state_.template direct_write_array<WORD_COUNT>(LSB, WIDTH, value, SW, SINGLEPULSE, "wide64_32.wide_reg.data");
        }

        class RdShadowOps {
        public:
            explicit RdShadowOps(Wide6432WideRegReg_data_Field* owner) : owner_(owner) {}
            std::array<data_t, WORD_COUNT> read() const {
                return owner_->owner_->state_.template read_field_shadow_array<WORD_COUNT>(LSB, WIDTH);
            }
        private:
            Wide6432WideRegReg_data_Field* owner_;
        };

        class WrShadowOps {
        public:
            explicit WrShadowOps(Wide6432WideRegReg_data_Field* owner) : owner_(owner) {}
            std::array<data_t, WORD_COUNT> read() const {
                return owner_->owner_->state_.template read_field_staged_array<WORD_COUNT>(LSB, WIDTH);
            }
            void write(const std::array<data_t, WORD_COUNT>& value) {
                owner_->owner_->state_.template shadow_write_array<WORD_COUNT>(LSB, WIDTH, value, "wide64_32.wide_reg.data");
            }
        private:
            Wide6432WideRegReg_data_Field* owner_;
        };

        RdShadowOps rd_shadow;
        WrShadowOps wr_shadow;

    private:
        Wide6432WideRegReg* owner_;
    };
    Wide6432WideRegReg_data_Field data;

private:
    detail::RegisterState<BusT, ThrowOnError> state_;
};

template <typename BusT>
class WideRoot {
public:
    static constexpr bool kThrowOnError = true;

private:
    using ContextT = detail::Context<BusT, kThrowOnError>;
    ContextT ctx_;
    addr_t instance_base_offset_;
public:

    explicit WideRoot(BusT& bus, addr_t base_address = 0)
        : ctx_(bus, base_address)
        , instance_base_offset_(0)
        , wide_reg(ctx_, static_cast<addr_t>(instance_base_offset_ + 0x0u))
        , rd_shadow(this)
        , wr_shadow(this)
    {
    }

    bool ok() const { return ctx_.ok(); }
    const std::string& last_error() const { return ctx_.last_error(); }
    void clear_error() { ctx_.clear_error(); }
    addr_t base_address() const { return ctx_.base_address; }

    class RdShadowOps {
    public:
        explicit RdShadowOps(WideRoot* owner) : owner_(owner) {}
        void read_hw() { owner_->rd_shadow_read_hw_impl(); }
    private:
        WideRoot* owner_;
    };

    RdShadowOps rd_shadow;

    class WrShadowOps {
    public:
        explicit WrShadowOps(WideRoot* owner) : owner_(owner) {}
        void flush() { owner_->wr_shadow_flush_impl(); }
        void flush_always() { owner_->wr_shadow_flush_always_impl(); }
    private:
        WideRoot* owner_;
    };

    WrShadowOps wr_shadow;

    Wide6432WideRegReg<BusT, kThrowOnError> wide_reg;

private:
    void rd_shadow_read_hw_impl() {
        if (wide_reg.supports_shadow_write()) wide_reg.rd_shadow.read_hw();
    }

    void wr_shadow_flush_impl() {
        if (wide_reg.supports_shadow_write()) wide_reg.wr_shadow.flush();
    }

    void wr_shadow_flush_always_impl() {
        if (wide_reg.supports_shadow_write()) wide_reg.wr_shadow.flush_always();
    }
};

} // namespace wide_demo
